.before_script_template: &ubuntu_before_script
  image: ubuntu:rolling
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -q -y --no-install-recommends valac gcc gettext itstool libgtk-3-dev libgtk-3-bin libgtksourceview-4-dev libmpc-dev libmpfr-dev libsoup2.4-dev libxml2-dev libgee-0.8-dev libvala-0.52 libhandy-1-dev python3-pip ninja-build
    - pip3 install --upgrade setuptools
    - pip3 install --no-cache-dir meson>=0.50.0

.before_script_template: &fedora_before_script
  image: fedora:latest
  before_script:
    - dnf install -y meson vala itstool gtk3-devel gtksourceview4-devel libmpc-devel mpfr-devel libsoup-devel libxml2-devel libgee-devel libhandy1-devel

.build_template: &meson_build
  stage: build
  script:
    - meson -Dui-tests=true _build .
    - ninja -C _build install
  artifacts:
    paths:
      - _build/
    expire_in: 2 hours

.test_template: &meson_test
  stage: test
  script:
    - broadwayd &
    - GDK_BACKEND=broadway ninja -C _build test

build:fedora:
  <<: *fedora_before_script
  <<: *meson_build

build:ubuntu:
  <<: *ubuntu_before_script
  <<: *meson_build

test:ubuntu:
  dependencies:
    - build:ubuntu
  <<: *ubuntu_before_script
  <<: *meson_test

test:fedora:
  dependencies:
    - build:fedora
  <<: *fedora_before_script
  <<: *meson_test

