include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
  image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
  variables:
    MANIFEST_PATH: "org.gnome.Calculator.json"
    FLATPAK_MODULE: "nautilus"
    APP_ID: "org.gnome.Calculator"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "gnome-calculator-dev.flatpak"
  extends: '.flatpak'

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
